### ISSUE TITLE
A couple of metrics are missing ignore_index

### ISSUE THREAD

**Issue by robmarkcole** [isaaccorley/a-change-detection-reality-check#1]
missing from:
- Accuracy
- FBetaScore
- Recall

**Comment by isaaccorley** [comment]
Good catch. While I'm recording these metrics I actually only used the classwise metrics for the results.

Other papers also report overall accuracy (OA) without ignoring the no-change class which is why I removed that.

**Comment by robmarkcole** [comment]
`without ignoring the no-change class` -  is that related to ignore_index?

**Comment by isaaccorley** [comment]
Yeah I'm not using the ignore_index in those metrics because there are no values I'm trying to ignore.
