### ISSUE TITLE
Checkpoint model

### ISSUE THREAD

**Issue by 66621** [isaaccorley/a-change-detection-reality-check#2]
Hello author, after reading your article, I strongly agree with your work and am very interested in it. But I can't find your checkpoint model, so I want to run a test on my own data set using your model. It will help me a lot in my present work. I would appreciate it if you could provide me with checkpoint models on both datasets.

**Comment by isaaccorley** [comment]
Hi @66621 I will upload the checkpoints to HuggingFace this weekend. Thanks for reminding me

**Comment by 66621** [comment]
Thank you very much！！！

**Comment by 66621** [comment]
I have another question, are all the versions of configurations needed for the code in your work the latest

**Comment by isaaccorley** [comment]
@66621 Yes but most of these are installed if you just install the latest version of torchgeo. image-bbox-slicer is only used for preprocessing the datasets into patches.

**Comment by 66621** [comment]
Ok，Thank you for your reply

**Comment by 66621** [comment]
Hello, The WH-CD dataset link you published earlier failed to open: HTTP Error 503. The service is unavailable. Could you please send me a link that can be used.

**Comment by isaaccorley** [comment]
The link worked fine for me. Can you try again? Thats the official dataset link (I did not publish this dataset) so I don't have an alternative.

**Comment by 66621** [comment]
ok，I will try again

**Comment by isaaccorley** [comment]
@66621 I've uploaded the checkpoints to HuggingFace. See the README for more info
