### ISSUE TITLE
Could you push an inference script?

### ISSUE THREAD

**Issue by Davidleeeeee** [isaaccorley/a-change-detection-reality-check#3]
Thanks for your contribution. Could you push an inference script?

**Comment by MyraBaba** [comment]
+1

**Comment by isaaccorley** [comment]
I don't currently have time for this but there are many examples online for loading a pytorch lightning model checkpoint using pytorch lightning and passing an image tensor through it like [this one](https://lightning.ai/docs/pytorch/stable/common/lightning_module.html#inference-in-production)
