### ISSUE TITLE
ImportError: cannot import name '_ExtractPatches' from 'torchgeo.transforms.transforms'

### ISSUE THREAD

**Issue by Davidleeeeee** [isaaccorley/a-change-detection-reality-check#4]
in my torchgeo 0.5.2 :
`D:\a-change-detection-reality-check\CD\Scripts\python.exe D:\a-change-detection-reality-check\train_levircd.py 
Traceback (most recent call last):
  File "D:\a-change-detection-reality-check\train_levircd.py", line 7, in <module>
    from src.datasets.levircd import LEVIRCDDataModule
  File "D:\a-change-detection-reality-check\src\datasets\levircd.py", line 5, in <module>
    from torchgeo.transforms.transforms import _ExtractPatches
ImportError: cannot import name '_ExtractPatches' from 'torchgeo.transforms.transforms' (D:\a-change-detection-reality-check\CD\lib\site-packages\torchgeo\transforms\transforms.py)

Process finished with exit code 1
`

**Comment by isaaccorley** [comment]
I see it hasn't been added to a release yet. You can install torchgeo from main using `pip install git+ https://github.com/microsoft/torchgeo.git`
