### ISSUE TITLE
torchgeo version?

### ISSUE THREAD

**Issue by lsh1994** [isaaccorley/a-change-detection-reality-check#7]
thanks for you work!I have some questions:
1. torchgeo version?
2. The backbone of the comparison model is different. Does this affect the conclusion?

**Comment by isaaccorley** [comment]
I used some features from the main branch which aren't in a release yet. You can install using `pip install git+https://github.com/microsoft/torchgeo.git`

Regarding the conclusion of the paper, I personally don't think so. Many of the models have additional parameters and layers in other ways so nothing is really apples to apples. The main point of the paper is just that nobody appears to be comparing to a good strong baseline of an older architecture. There's not a large jump in performance when using recent proposed architectures.
